onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /datapath_tb/CLK
add wave -noupdate /datapath_tb/nRST
add wave -noupdate /datapath_tb/DUT/pc_count_four_output
add wave -noupdate /datapath_tb/DUT/next_pc_count
add wave -noupdate /datapath_tb/DUT/current_pc_count
add wave -noupdate /datapath_tb/DUT/pcselect
add wave -noupdate /datapath_tb/dpif/halt
add wave -noupdate /datapath_tb/dpif/ihit
add wave -noupdate /datapath_tb/dpif/imemREN
add wave -noupdate /datapath_tb/dpif/imemload
add wave -noupdate /datapath_tb/dpif/imemaddr
add wave -noupdate /datapath_tb/dpif/dhit
add wave -noupdate /datapath_tb/dpif/datomic
add wave -noupdate /datapath_tb/dpif/dmemREN
add wave -noupdate /datapath_tb/dpif/dmemWEN
add wave -noupdate /datapath_tb/dpif/flushed
add wave -noupdate /datapath_tb/dpif/dmemload
add wave -noupdate /datapath_tb/dpif/dmemstore
add wave -noupdate /datapath_tb/dpif/dmemaddr
add wave -noupdate /datapath_tb/DUT/PC_INIT
add wave -noupdate /datapath_tb/DUT/CLK
add wave -noupdate /datapath_tb/DUT/nRST
add wave -noupdate /datapath_tb/DUT/read_data_one_output
add wave -noupdate /datapath_tb/DUT/read_data_two_output
add wave -noupdate /datapath_tb/DUT/write_register_location
add wave -noupdate /datapath_tb/DUT/write_register_value
add wave -noupdate /datapath_tb/DUT/ALUsrc
add wave -noupdate /datapath_tb/DUT/memtoreg
add wave -noupdate /datapath_tb/DUT/shift
add wave -noupdate /datapath_tb/DUT/signzero
add wave -noupdate /datapath_tb/DUT/ALUop
add wave -noupdate /datapath_tb/DUT/JAL
add wave -noupdate /datapath_tb/DUT/regwrite
add wave -noupdate /datapath_tb/DUT/regdst
add wave -noupdate /datapath_tb/DUT/branch
add wave -noupdate /datapath_tb/DUT/request_dmemREN
add wave -noupdate /datapath_tb/DUT/request_dmemWEN
add wave -noupdate /datapath_tb/DUT/request_dmemREN_output
add wave -noupdate /datapath_tb/DUT/request_dmemWEN_output
add wave -noupdate /datapath_tb/DUT/alu_input_one
add wave -noupdate /datapath_tb/DUT/alu_input_two
add wave -noupdate /datapath_tb/DUT/ALU_OPCODE
add wave -noupdate /datapath_tb/DUT/ALU_OUTPUT
add wave -noupdate /datapath_tb/DUT/ALU_NEGATIVE
add wave -noupdate /datapath_tb/DUT/ALU_OVERFLOW
add wave -noupdate /datapath_tb/DUT/ALU_ZERO
add wave -noupdate /datapath_tb/DUT/signzero_output
add wave -noupdate /datapath_tb/DUT/writedata_output
add wave -noupdate /datapath_tb/DUT/branch_count_output
add wave -noupdate /datapath_tb/DUT/branch_xnor_output
add wave -noupdate /datapath_tb/DUT/branch_mux_output
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {20 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {49 ns}
